# backend/pdf_export.py — NEXA PDF export
# Provides one function called from app.py:
# generate_chat_pdf(messages, title) → io.BytesIO
# uses reportlab to build the PDF entirely in memory (no temp files).
# safe for GCP Cloud Run / App Engine read-only filesystems.

import io
import datetime
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, HRFlowable
)


# STYLES
def _build_styles():
    base = getSampleStyleSheet()

    user_style = ParagraphStyle(
        "UserLabel",
        parent=base["Normal"],
        fontName="Helvetica-Bold",
        fontSize=10,
        textColor=colors.HexColor("#1a56db"),
        spaceAfter=2,
    )

    user_text_style = ParagraphStyle(
        "UserText",
        parent=base["Normal"],
        fontName="Helvetica",
        fontSize=10,
        textColor=colors.HexColor("#1e3a5f"),
        spaceAfter=8,
        leftIndent=12,
    )

    assistant_label_style = ParagraphStyle(
        "AssistantLabel",
        parent=base["Normal"],
        fontName="Helvetica-Bold",
        fontSize=10,
        textColor=colors.HexColor("#166534"),
        spaceAfter=2,
    )

    assistant_text_style = ParagraphStyle(
        "AssistantText",
        parent=base["Normal"],
        fontName="Helvetica",
        fontSize=10,
        textColor=colors.HexColor("#111827"),
        spaceAfter=8,
        leftIndent=12,
    )

    title_style = ParagraphStyle(
        "ChatTitle",
        parent=base["Title"],
        fontName="Helvetica-Bold",
        fontSize=18,
        textColor=colors.HexColor("#111827"),
        spaceAfter=4,
    )

    meta_style = ParagraphStyle(
        "ChatMeta",
        parent=base["Italic"],
        fontName="Helvetica-Oblique",
        fontSize=9,
        textColor=colors.HexColor("#6b7280"),
        spaceAfter=16,
    )

    return {
        "title":           title_style,
        "meta":            meta_style,
        "user_label":      user_style,
        "user_text":       user_text_style,
        "assistant_label": assistant_label_style,
        "assistant_text":  assistant_text_style,
    }


# MAIN EXPORT FUNCTION
def generate_chat_pdf(
    messages: list[dict],
    title: str = "Chat Conversation",
) -> io.BytesIO:
    """
    Builds a PDF from a list of chat messages entirely in memory.

    Parameters:
        messages — list of {"role": "user"|"assistant", "content": "..."}
        title    — heading shown at the top of the PDF

    Returns:
        io.BytesIO buffer — ready to pass directly to Flask's send_file()
    """

    buffer = io.BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=0.85 * inch,
        leftMargin=0.85 * inch,
        topMargin=0.85 * inch,
        bottomMargin=0.85 * inch,
    )

    styles = _build_styles()
    story  = []

    # title and metadata header
    story.append(Paragraph(title, styles["title"]))
    story.append(Paragraph(
        f"Downloaded: {datetime.datetime.utcnow().strftime('%B %d, %Y at %H:%M UTC')}",
        styles["meta"]
    ))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#e5e7eb")))
    story.append(Spacer(1, 14))

    # message blocks
    for msg in messages:
        role    = msg.get("role", "unknown")
        content = msg.get("content", "").strip()

        # escape characters that confuse ReportLab's XML parser
        content = (
            content
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
        )

        if role == "user":
            story.append(Paragraph("You:", styles["user_label"]))
            story.append(Paragraph(content, styles["user_text"]))
        else:
            story.append(Paragraph("NEXA:", styles["assistant_label"]))
            story.append(Paragraph(content, styles["assistant_text"]))

        story.append(HRFlowable(
            width="100%", thickness=0.5,
            color=colors.HexColor("#f3f4f6"),
            spaceAfter=10
        ))
        story.append(Spacer(1, 4))

    # footer note
    story.append(Spacer(1, 20))
    story.append(Paragraph(
        "Generated by NEXA — for reference purposes only.",
        ParagraphStyle(
            "Footer",
            fontName="Helvetica-Oblique",
            fontSize=8,
            textColor=colors.HexColor("#9ca3af"),
        )
    ))

    doc.build(story)
    buffer.seek(0)
    return buffer
